### ISSUE TITLE
Your email regex is broken.  Please don't use this

### ISSUE THREAD

**Issue by RandalSchwartz** [shirsh94/flutter_regex#1]
No, please don't use this regex to validate email.  It's wrong.  The shortest regex to validate an RFC822 email address is about 2400 characters, and is given in https://www.ex-parrot.com/pdw/Mail-RFC822-Address.html.  Anything shorter is WRONG, unless you're using a grammar, as package:email_validator properly does.  Use that for Dart/Flutter please.

**Comment by shirsh94** [comment]
Thank you for your input. While I understand your concern, the regex I've used in the flutter_regex plugin is designed to validate basic email IDs that are commonly used. It's intended for simpler use cases and doesn't aim to cover the entire RFC822 specification.

I appreciate your suggestion to use the email_validator package, but I'm aware that it has its own set of issues, as you've mentioned. I believe developers should choose the validation method that best suits their needs, whether it's a more comprehensive solution like email_validator or a simpler regex-based approach like the one in flutter_regex.

If you have any further feedback or suggestions, feel free to share them. I'm closing this issue for now, but please don't hesitate to open a new one if you have other concerns or questions.
